.tfsec:
  stage: test
  image: #a simple mix between liamg/tfsec and hashicorp/terraform
    name: linuxbandit/terraform-with-tfsec:v0.12.9
    entrypoint: [""]

tfsec:
  extends: .tfsec
  script:
    - |
      terraform --version
      terraform init -backend=false
    - tfsec .
  only:
    - tags
    - merge_requests
  allow_failure: true
  variables:
    GIT_DEPTH: 1